### ISSUE TITLE
Absolute coordinates is Unobservable with the input 

### ISSUE THREAD

**Issue by Grant2Grant** [Ninebell/GaneratedHandsForReal_TIME#1]
Hi, I noted that you're implementing the GANerated Hands, which I'm working on. But I'm afraid that there's something wrong in your code.
As we know, parameter can be estimated only when the input contains enough information. To make it clear, one cannot know his latitude and longitude only by the environment he sees around, even though he can estimate his position in the current environment by looking around. Also, you can figure out where is the forward of the boat by looking around the board, but you don't know if you are forward to the north with the same information.

In the same way, your cannot estimate the absolute coordinates of the hand when you just input the cropped image of hands to the model. (Yes you input the crop parameter on training, but it don't serve as information for the model to estimate the output before projlayer. In a word, the output 3d position of your network is equal up to a translation.

BTW, I'm trying to implement the paper since the author don't release the code. We can discuss the progress via email. My email address is emojlearning@zju.edu.cn

**Comment by Ninebell** [comment]
hello, I read this issue on now. Actually, I also found your topic. And I just adopt the crop parameter for making rendered heatmap but it is not same to paper, So I read the paper again.
In paper, they made intermediate 3D position and final 3d output is ratio position(m0 and w distance is 1). 
Now I`m worried about how to make rendered heatmap from ratio postion.

**Comment by Grant2Grant** [comment]
https://github.com/piani/Pia-in/tree/master/CVPR2018_Model

This seems to be the author's implementation, but I'm not sure. It use orthogonal projection instead of perspective projection. Since I know little about caffe I didn't manage to run it successfully.

**Comment by Ninebell** [comment]
Thank you about your help. I committed my new code about projLayer.
And I think [model_summary](https://github.com/piani/Pia-in/blob/master/CVPR2018_Model/RegNet_deploy.prototxt) will be helpful for making model.
