### ISSUE TITLE
GeoConGAN

### ISSUE THREAD

**Issue by flyyyyer** [Ninebell/GaneratedHandsForReal_TIME#11]
How can I train the GeoConGAN  in my own  dataset?

**Comment by Ninebell** [comment]
Hello sir,
I wiil update soon.
Anyway, if you want to train the GeoConGAN,
1. You need to train the Silnet first
2. Call the sillnet into the GeoConGAN
3. Set the data path two domain for training.
4. And start the train~.

**Comment by flyyyyer** [comment]
My coding is not good, emmm...., so I will be appreciated for you update as soon as possible, thank you very much! 
I hope you can give a demo to train on the horse2zebra, so I can just change the dataset path to my own dataset.

**Comment by Ninebell** [comment]
@flyyyyer if you want to train horse2zebra, you need silluet about horse and zebra. Or you mean training cyclegan?

**Comment by flyyyyer** [comment]
Oh, I just want to train the GeoConGAN on my hand dataset

**Comment by Ninebell** [comment]
@flyyyyer 
I had update code about training in [here](https://github.com/Ninebell/GaneratedHandsForReal_TIME/blob/master/GeoConGAN/GeoconGAN_main.py). but readme is not yet. 

and you keep the dataset tree like me or you must customize code about calling data.

**Comment by flyyyyer** [comment]
Thank you for your sharing. 
In GeoconGan_main.py, the input has the mask image, but I only has real images and synth images.
How can I get the mask images? I dont's know how to process the hand RGB images with background to hand mask images.

**Comment by Ninebell** [comment]
@flyyyyer 
Hmmm.... I'm sorry about that. My image process code was hard code. and origin real data's mask images had some error. my histories were in [here](https://github.com/Ninebell/GaneratedHandsForReal_TIME/blob/master/GeoConGAN/ImagePreprocess.py) but just read and note only.

**Comment by flyyyyer** [comment]
So I can't train the GeoconGan if I don't have the mask images.
