### ISSUE TITLE
some problems about test!

### ISSUE THREAD

**Issue by visonpon** [Ninebell/GaneratedHandsForReal_TIME#12]
Hi, @Ninebell thanks for your great re-implement work, but I have some problems when tested on my own images.

In [https://github.com/Ninebell/GaneratedHandsForReal_TIME/blob/master/test_regnet.py#L21](url) the `crop_param/joint_3d/joint_3d_rate...`  didn't use in the final result , so I simplify it to only read an image, the output heatmap is a (32,32,21) array, then I extract the max value's coordinates in each heatmap and draw those coordinates,  the result should be the 21 landmarks of the hand but it looks bad.

I'm curious about where am I wrong? hope can receive your help,thanks

**Comment by zuoqing1988** [comment]
The ProjLayer is wrong. 

s (u,v,1)^T = (fx ,0, cx; 0, fy,cy,0,0,1) * (x,y,z)^T

3D coordinate (x,y,z) should be readed from "*_joint_pos_global.txt". Intrinsic matrix is fixed to 
[ 617.173,       0, 315.453,
        0, 617.173, 242.259,
        0,       0,       1]
Then (u,v) should be shifted and scaled according to "*_crop_params.txt"

**Comment by Ninebell** [comment]
Hello, @visonpon .
test_regney.py is not done. I'm implementing it.
You can see the use of joint_3d_rate in https://github.com/Ninebell/GaneratedHandsForReal_TIME/blob/master/RegNet/regnet.py #L173 .

And about your qurious of heatmap size. I had thought like you.  I just resized it to original image size. Actually, it may be caused some problem. But... I think that it doesn't cause critical problem. So I just passed it. 

In paper, you can see skeleton fitting functions. it need to use for fitting. I will implementing as soon as. May be it done, accuracy can be upgrade.

Thank you for issue.

**Comment by Ninebell** [comment]
Hello @zuoqing1988 
I think that you thought projLayer need to projection 3D to 2D same with label data.
if you show the original paper, projlayer's input was not perfectly 3D label data. just intermediate 3D position. so author use projlayer with orthogonal projection.

**Comment by zuoqing1988** [comment]
@Ninebell The target 'heatmap_final' is generated using "_joint2D.txt".
If you don't use the "_crop_params.txt" and intrinsic matrix, you can never project "joint3D_rate" correctly.
"joint3d_rate" is relative coordinates. One joint is always (0,0,0) no matter how the 256*256 image is cropped.

**Comment by zuoqing1988** [comment]
The coordinate systems of the 256x256 image and the original 640x480 image are not equal. Even if you use orthogonal projection to approximate, you still need to translate and scale the 3D coordinates.

**Comment by Ninebell** [comment]
@zuoqing1988 Thank you for your regard.

Hmm.. when I read the paper, I understood that _joint2D.txt values were made _crop_params.txt and joint_3d_global.txt

Because data set is GANerated and it's original datas were just 3D position didn't have 2D position. 

so camera intrinsic matrix was used to project  for 3D to 2D position.

And Input of regnet is not 640x480, but cropped image size of 256x256 from 640x480.

Anyway, my opinion is that intrinsic matrix was not used in training, just in made dataset.

may be it's my fault, because I'm not good to english interpretation.

**Comment by zuoqing1988** [comment]
@Ninebell 
It's an example to show how "joint_pos_global.txt" can be projected to "joint2D.txt"
![image](https://user-images.githubusercontent.com/20920889/68363387-a2085080-0165-11ea-8ef4-b2c97617bdd1.png)

[test_proj.zip](https://github.com/Ninebell/GaneratedHandsForReal_TIME/files/3818023/test_proj.zip)

**Comment by Ninebell** [comment]
@zuoqing1988 
Yes, I know it.

**Comment by Franziska-Mueller** [comment]
Hi,

we don't use any intrinsic matrix in training.
You can check my supplementary document (https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/content/GANeratedHands_CVPR2018_Supp.pdf) about more information about the projection layer.

**Comment by zuoqing1988** [comment]
@Franziska-Mueller 
Thanks.
