### ISSUE TITLE
Finished yet?

### ISSUE THREAD

**Issue by KobayashiLiu** [Ninebell/GaneratedHandsForReal_TIME#13]
hello,I'm learning this paper.In README, some parts in the 'tree' are noted by 'yet'.
Are they finished yet, or still working on them ?
Thanks

**Comment by Ninebell** [comment]
@KobayashiLiu , hello I'm still working on them. 
I'm implementing now about skeleton fitting. But some huddle encountered. 
So as fast as soon, I will update code.
Thank you.

and I was re-learning about Regnet. Former training has some problem and I will update about new.
