### ISSUE TITLE
joint_3d or joint_3d_rate

### ISSUE THREAD

**Issue by www516717402** [Ninebell/GaneratedHandsForReal_TIME#16]
thank you for great project. joint_3d param not use in Train step and Test step. how distinguish between joint_3d and joint_3d_rate?

**Comment by Ninebell** [comment]
3d joint is evaluated by 3d pck. I don't implement it. because I need skeleton fitting function for evaluating final output, but I don't know how to implement. so I stop the upgrade this repository and now focus to other repository in private. 

if I realize about skeleton fitting, I will start upgrade this repository. thank you.

and you can see about 3d pck in 4.1 Quantative evaluation, paper

**Comment by Ninebell** [comment]
I`m sorry. I misunderstood about your question. I used 3d joint rate in training data.
you can show it in regnet.py line 159. and crop_param, joint 3d is just trace about some experiment. they were not used now.

**Comment by www516717402** [comment]
Thanks for reply. 3d joint rate means points in camera space ?

**Comment by www516717402** [comment]
I have always been confused about 3D coordinates. some paper predicate Z in camera space, X,Y in image space. Some paper used X,Y in image space, also used X1,Y1,Z1 in camera space or world space.

**Comment by Ninebell** [comment]
you can find  "the middle finger metacarpophalangeal (MCP) joint is at the origin and the distance between the wrist joint and the middle MCP joint is 1" this sentence in paper.

**Comment by Ninebell** [comment]
this paper hand is made by synthetic. synthetic image were changed real by GeoConGAN.
 so they had 3d point themselves.  Just use this 3d point to 3d point rate. I don't know about other paper. but what I understand is different using synthetic image with GeoConGAN for easily get 3d point.

**Comment by www516717402** [comment]
Thank you for your quick reply. I will read paper by your advise. About 3D labels, such paper are different:  [paper one](https://github.com/3d-hand-shape/hand-graph-cnn), [paper two](https://github.com/CalciferZh/minimal-hand)
