### ISSUE TITLE
Have you finished the code in 'RegNet' folder of this project?

### ISSUE THREAD

**Issue by Peng154** [Ninebell/GaneratedHandsForReal_TIME#2]
It's awesome that you reimplement the project GaneratedHandsForReal_TIME while the author does not release the source code. Can i read and use your code  in 'RegNet' folder of this project now with confidence? Have you completed the test for the regnet code?

Thanks.

**Comment by Ninebell** [comment]
I`m testing now. RegNet in regnet.py is not same with author model.  and RegNet in regnet_.py is I tried to same with original.

**Comment by Peng154** [comment]
Thanks a lot.Maybe i can start to modify your newest code for fitting my hand dataset.

**Comment by Ninebell** [comment]
Could u fork my github? I want know how to modify it. Thank you for stopping by.

**Comment by Peng154** [comment]
No problem, but what i am doing now is just trying to transform the format of  my dataset to the format of paper's released dataset.
