### ISSUE TITLE
About weights

### ISSUE THREAD

**Issue by redorangeyellowy** [Ninebell/GaneratedHandsForReal_TIME#21]
Hello,

I want to implement GeoConGAN, but I can't access weight from the link below.

https://drive.google.com/drive/folders/1hfH_r1_LjBETMK3r0zbsOyTIkvsyqPbQ

I wonder if you would like to share the weight file.

**Comment by EvertonCa** [comment]
hello! 

I asked the authors to provide me the weights. Did you tried that?

**Comment by redorangeyellowy** [comment]
Could you share the weight you received with me?

**Comment by EvertonCa** [comment]
I don't think it would be ethical for me to share the weights, since I do not own them. I was only allowed to use them for my research. I suggest you try contacting the author of the paper.

**Comment by Ninebell** [comment]
@redorangeyellowy 
hello,
I don't manage this repository anymore. and the weight file that you requested was deleted because Google Drive is full of capacity.
I'm sorry about that.

**Comment by redorangeyellowy** [comment]
That's very sad news. I got it.
