### ISSUE TITLE
regnet.h5 -- regnet_main.py

### ISSUE THREAD

**Issue by TingHungEricLin** [Ninebell/GaneratedHandsForReal_TIME#4]
Hi,

Does line 34's load_weights (regnet.h5) come from train_on_batch results? Or from test_on_batch?

If I didn't use line 34 (regnet_main.py), will it cause any failure?

I am not sure where I would to get the same regnet.h5 as yours!

**Comment by Ninebell** [comment]
Hello, sir.
I`m sorry about that. I don't have some page for supplying weight file. 
So if you need it, tell me your email. I will send you regnet.h5

May be you confused.  test on batch is called in train on batch.

and I didn't expect some attention to my repository. 
I will make more appropriate soon.

**Comment by TingHungEricLin** [comment]
Here is my e-mail address "ericthlin@gmail.com"!

By the way, the current regnet focus on 32*32! I am trying on 64*64! Any suggestion?

**Comment by Ninebell** [comment]
Hello, sir.
Does it mean the size of rendering heat-map??
May be you just change 32 to 64 in RenderingLayer, ProjLayer and line36 in regnet_.py, and so on.

I`m sorry to that;;  my code is too smell. I will change it to easy for using.

**Comment by TingHungEricLin** [comment]
Dear Ninebell,

Will update to you soon about the updating to 64*64 in RenderingLayer. Change on both ProjLayer and regnet_ files...

**Comment by darrenchen0226** [comment]
Dear Ninebell,

Here is my email address. 
darren0226@gmail.com
May I have your regnet.h5 based on 32x32 in rendering layer?
Using test_regnet.py with our trained model seems not to have good prediction.
