### ISSUE TITLE
training_GANS

### ISSUE THREAD

**Issue by xiaoguitoucode** [Ninebell/GaneratedHandsForReal_TIME#6]
HI,thanks for your contibution.I want to train the GeoConGAN network,but meet some problems:
   1.how to get silnet.h5
   2.how to train the GeoConGAN network
Thanks for your work again.
Looking forward to your reply!

**Comment by Ninebell** [comment]
If you need Ganerted Dataset you can download in [here](https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/GANeratedDataset.htm)
