### ISSUE TITLE
Weight of Silnet and GeoConGan

### ISSUE THREAD

**Issue by hizircanbayram** [Ninebell/GaneratedHandsForReal_TIME#7]
Hello!
I was wondering how we can access weights of Silnet and GeoConGan. Is there any trained model that you can share with us? If there was not, can we get those weight training your projects? If so, how?
Thanks in advance.

**Comment by Ninebell** [comment]
hello, if you tell me your email, I will send you

**Comment by hizircanbayram** [comment]
Thanks! 
hizircanbayram@gmail.com

**Comment by TingHungEricLin** [comment]
Dear Ninebell,

Would I get, too? ericthlin@gmail.com

**Comment by TingHungEricLin** [comment]
Dear Ninebell,

Would you please re-send this to me? I made mistake, so you sending email (for GeoConGan) delete on google clouding...
Please, and thanks...

**Comment by TingHungEricLin** [comment]
For 64 * 64, I did change 
heatmaps_pred3D = RenderingLayer([64,64], coeff=1, name='heatmaps_pred3D')(projLayer) -- regnet_.py 
&
self.base = k_b.ones((1, 64*64), dtype=np.float) -- ProjLayer.py...

But, get a wrong messages...
concat_pred_rendered = concatenate([conv, conv_rendered_3]) ...
 A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 8, 8, 256), (None, 16, 16, 128)]

Do I miss to change another code?

**Comment by xiaoguitoucode** [comment]
Hi, Could you send me the weights of Silnet and GeoConGAN? Thanks !
1130455704@qq.com
