### ISSUE TITLE
About whites and masks

### ISSUE THREAD

**Issue by hizircanbayram** [Ninebell/GaneratedHandsForReal_TIME#8]
When located at GaneratedHandsForReal_TIME-master\GeoConGAN\ImagePreprocess.py, line 282,283(in function hand_image_pair_path(),
what kind of images are we supposed to put in those directories?

**Comment by Ninebell** [comment]
hello sir,

Synth data can be download in [here](https://handtracker.mpi-inf.mpg.de/projects/OccludedHands/SynthHands.htm).

Real & GANerated data can be download in [here](https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/GANeratedDataset.htm).

If you want to play GeoConGAN, you need to crop the hand from original image in real data-set.

In real dataset, It's mask images are not good to apply. So you customize the code for masking. 
In my case, I'm not expert to image process so just using basic image process like threshold convex hull in opencv and Just Do handwork(Check the wrong image).

**Comment by Ninebell** [comment]
I recommend you just my GeoConGAN model for understand. 
and using Ganerated Data in [here](https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/GANeratedDataset.htm)

**Comment by hizircanbayram** [comment]
Thanks for the comment! I'm downloading the real hand data set. So as to understand it better, let me clarify one more thing though... Will I be able to find the directories whites and masks in this real hand data set? I mean, I will try to generate my own GANarated images but your file structure confused me a bit. Can you share one sample from each directories('whites' and 'masks') so that I can understand what are in them?

**Comment by Ninebell** [comment]
when you downloaded the real data-set, you can show directories color and mask.
![image](https://user-images.githubusercontent.com/41539605/67020177-bd6cd680-f138-11e9-945a-a178d115c755.png)
may be you confused about whites. whites is just original image.

Method in line 270-289 did not use. I call the path using method in line 17.

**Comment by hizircanbayram** [comment]
Thank you. This repo is a great opportunity and thank you for your cooperation.

**Comment by Ninebell** [comment]
Thank you.
I'll be grateful if you give me star to this repository.

**Comment by hizircanbayram** [comment]
Done! (Y)
